zimzim_bundles_world_cup_zimzim_worldcup_game:
    resource: "@ZIMZIMBundlesWorldCupBundle/Resources/config/routing/game.yml"
    prefix:   /game/

ZIMZIMBundlesWorldCupBundle_zimzim_worldcup_userbet:
    resource: "@ZIMZIMBundlesWorldCupBundle/Resources/config/routing/userbet.yml"
    prefix:   /userbet/

zimzim_worldcup_score:
    pattern:  /score/
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Score:index" }
    requirements: { _method: get }

zimzim_worldcup_score_ranking:
    pattern:  /ranking/
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Score:ranking" }
    requirements: { _method: get }

zimzim_bundles_worldcup_homepage:
    pattern:  /
    defaults: { _controller: ZIMZIMBundlesWorldCupBundle:Default:index }
