zimzim_worldcup_userbet:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:UserBet:index" }

zimzim_worldcup_userbet_with_game:
    pattern: /game/{id}/bet/
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:UserBet:betwithgame" }
    requirements: { _method: post|get }
